---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "carts.name" . }}-primary
  labels:
    app: {{ template "carts.name" . }}
    chart: {{ template "carts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ template "carts.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "carts.name" . }}-canary
  labels:
    app: {{ template "carts.name" . }}
    chart: {{ template "carts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ template "carts.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: canary-{{ template "carts.name" . }}-ingress
spec:
  rules:
  - host: canary.{{ template "carts.name" . }}.{{ .Values.service.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "carts.name" . }}-canary
          servicePort: {{ .Values.service.port }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: primary-{{ template "carts.name" . }}-ingress
spec:
  rules:
  - host: primary.{{ template "carts.name" . }}.{{ .Values.service.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "carts.name" . }}-primary
          servicePort: {{ .Values.service.port }}